springdoc:
  swagger-ui:
    path: /v1/swagger
  logging:
    level:
      be.vlaanderen.informatievlaanderen: DEBUG
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
