global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "ldio-workbench"
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["ldio-workbench:8080"]
